plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

@OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
kotlin {
    androidTarget()

    jvm("desktop") {
        // Configure desktop application
    }

    // iOS targets
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "SignaturePadApp"
            isStatic = true
        }
    }

    // Web targets
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "signaturepadapp.js"
            }
        }
        binaries.executable()
    }

    js(IR) {
        browser {
            commonWebpackConfig {
                outputFileName = "signaturepadapp.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        commonMain {
            dependencies {
                // Signature Pad library
                implementation(projects.signaturePad)

                // Compose Multiplatform
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(compose.materialIconsExtended)
            }
        }

        androidMain {
            dependencies {
                // Android-specific dependencies
                implementation(compose.uiTooling)
                implementation(compose.preview)
                implementation(libs.activity.compose)
                implementation(libs.core.ktx)
            }
        }

        val desktopMain by getting {
            dependencies {
                // Desktop-specific dependencies
                implementation(compose.desktop.currentOs)
            }
        }

        iosMain {
            dependencies {
                // iOS-specific dependencies if needed
            }
        }

        val wasmJsMain by getting {
            dependencies {
                // Wasm-specific dependencies if needed
            }
        }

        jsMain {
            dependencies {
                // JS-specific dependencies if needed
            }
        }
    }
}

android {
    namespace = "com.tuppersoft.signaturepad.sample"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.tuppersoft.signaturepad.sample"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
    }
}

// Note: Desktop, Web and iOS run tasks are automatically generated by Kotlin Multiplatform plugin:
// - Desktop: ./gradlew :app:runDesktop
// - Web (Wasm): ./gradlew :app:wasmJsBrowserDevelopmentRun
// - Web (JS): ./gradlew :app:jsBrowserDevelopmentRun

compose.desktop {
    application {
        mainClass = "com.tuppersoft.signaturepad.sample.desktop.MainKt"

        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb
            )
            packageName = "Signature Pad KMP Demo"
            packageVersion = "1.0.0"

            macOS {
                iconFile.set(project.file("src/desktopMain/resources/icon.icns"))
            }
            windows {
                iconFile.set(project.file("src/desktopMain/resources/icon.ico"))
            }
            linux {
                iconFile.set(project.file("src/desktopMain/resources/icon.png"))
            }
        }
    }
}

